networks = [
    # Networks to include the entire length of as one road.
    # US Interstates:
    "US:I",
    # US Routes:
    "US:US",
    # US State Routes:
    "US:AL",
    "US:AK",
    "US:AR",
    "US:AZ",
    "US:CA",
    "US:CO",
    "US:CT",
    "US:DC",
    "US:DE",
    "US:FL",
    "US:GA",
    "US:HI",
    "US:IA",
    "US:ID",
    "US:IL",
    "US:IN",
    "US:KS",
    "US:KY",
    "US:LA",
    "US:MA",
    "US:MD",
    "US:ME",
    "US:MI",
    "US:MN",
    "US:MO",
    "US:MS",
    "US:MT",
    "US:NC",
    "US:NE",
    "US:NH",
    "US:NJ",
    "US:NV",
    "US:NM",
    "US:NY",
    "US:ND",
    "US:OH",
    "US:OK",
    "US:OR",
    "US:PA",
    "US:PR",
    "US:RI",
    "US:SC",
    "US:SD",
    "US:TN",
    "US:TX",
    "US:UT",
    "US:VA",
    "US:VT",
    "US:WA",
    "US:WI",
    "US:WV",
    "US:WY",
]

[crs]
osm = "EPSG:4326" # WGS-84
metric = "EPSG:5070" # CONUS Albers Metric
output = "EPSG:4326" # WGS-84

[search]
# Parameters for finding roads.
max_dist = 50 # Max meters (in metric CRS) to search for nearby road
consec_pts = 3 # Min number of consecutive points to count as road match

[output]
# Output filenames, relative to the --output directory
csv = "roads.csv"
gpkg = "20k_roads.gpkg"