networks = [
    # Networks to include the entire length of as one road.
    # Europe:
    "e-road",
    # Australia:
    "AU",
    "AU:NSW",
    "AU:VIC",
    "AU:WA:NR", "AU:WA:S",
    # Canada:
    "CA:transcanada",
    "CA:BC",
    "CA:ON:primary", "CA:ON:private_toll", "CA:ON:Toronto:Expressway",
    # Germany:
    "BAB", # Autobahn
    "DE:national",
    # Iceland:
    "IS",
    # New Zealand:
    "NZ:SH",
    # Japan:
    "JP:national", "JP:E",
    # UK:
    "UK:motorway",
    # US Interstates:
    # Deliberately omitting "US:I:Alternate" as it has too many paths that don't make sense as one road.
    "US:I", "US:I:Business", "US:I:Business:Loop", "US:I:Express", "US:I:Express:Toll", "US:I:Spur", "US:I:Truck",
    # US Routes:
    "US:US", "US:US:Alternate", "US:US:Business", "US:US:Bypass", "US:US:Express",
    # US State Routes:
    "US:AL",
    "US:AK",
    "US:AR",
    "US:AZ", "US:AZ:Loop",
    "US:BIA",
    "US:CA", "US:CA:Business", "US:CA:Express", "US:CA:Truck",
    "US:CO", "US:CO:E470",
    "US:CT",
    "US:DC",
    "US:DE",
    "US:FL", "US:FL:CR", "US:FL:Toll", "US:FL:Turnpike",
    "US:GA",
    "US:HI",
    "US:IA",
    "US:ID",
    "US:IL",
    "US:IN",
    "US:KS",
    "US:KY", "US:KY:AA", "US:KY:Business", "US:KY:Parkway",
    "US:LA",
    "US:MA",
    "US:MD",
    "US:ME",
    "US:MI",
    "US:MN",
    "US:MO",
    "US:MS",
    "US:MT",
    "US:NC", "US:NC:Toll",
    "US:NE",
    "US:NH",
    "US:NJ", "US:NJ:GSP", "US:NJ:NJTP",
    "US:NV", "US:NV:Clark",
    "US:NM",
    "US:NY", "US:NY:Parkway",
    "US:ND",
    "US:OH", "US:OH:Bypass", "US:OH:Truck",
    "US:OK", "US:OK:Greer", "US:OK:Jackson", "US:OK:Kiowa", "US:OK:Rogers",
    "US:OR",
    "US:PA",
    "US:PR", "US:PR:Primary",
    "US:RI",
    "US:SC",
    "US:SD",
    "US:TN", "US:TN:primary",
    "US:TX", "US:TX:CTRMA:Express", "US:TX:Express:Toll", "US:TX:FM", "US:TX:Loop", "US:TX:Loop:Express:Toll", "US:TX:Spur",
    "US:UT",
    "US:VA", "US:VA:Secondary",
    "US:VT",
    "US:WA", "US:WA:Spur",
    "US:WI",
    "US:WV",
    "US:WY",
]
networks_unsigned = [
    # Networks to allow even if unsigned (no 'ref'). Network must still be in networks list above.
    "US:FL:Turnpike",
    "US:KY:Parkway",
]

[crs]
osm = "EPSG:4326" # WGS-84
metric = "EPSG:8857" # WGS 84 / Equal Earth Greenwich (metre)
output = "EPSG:4326" # WGS-84

[search]
# Parameters for finding roads.
max_dist_track = 50 # Max meters (in metric CRS) to search for nearby way from track
max_dist_gap = 100 # Max meters (in metric CRS) to search for way with same name when tracing named roads

consec_pts = 4 # Min number of consecutive points to count as road match
highway_types = [
    # Filter for OSM highway tag
    'motorway',
    'trunk',
    'primary',
    'secondary',
    'tertiary',
    'unclassified',
    'residential',
    'motorway_link',
    'trunk_link',
    'primary_link',
    'secondary_link',
    'living_street',
]
distinctness_ratio = 0.05 # Fraction of ways of a named road that must be distinct from an overlapping route to keep the road
