networks = [
    # Networks to include the entire length of as one road.
    # US Interstates:
    "US:I", "US:I:Business", "US:I:Business:Loop", "US:I:Express", "US:I:Express:Toll",
    # US Routes:
    "US:US", "US:US:Business", "US:US:Express",
    # US State Routes:
    "US:AL",
    "US:AK",
    "US:AR",
    "US:AZ",
    "US:CA",
    "US:CO",
    "US:CT",
    "US:DC",
    "US:DE",
    "US:FL", "US:FL:Toll",
    "US:GA",
    "US:HI",
    "US:IA",
    "US:ID",
    "US:IL",
    "US:IN",
    "US:KS",
    "US:KY", "US:KY:Business",
    "US:LA",
    "US:MA",
    "US:MD",
    "US:ME",
    "US:MI",
    "US:MN",
    "US:MO",
    "US:MS",
    "US:MT",
    "US:NC",
    "US:NE",
    "US:NH",
    "US:NJ",
    "US:NV",
    "US:NM",
    "US:NY",
    "US:ND",
    "US:OH", "US:OH:Bypass", "US:OH:Truck",
    "US:OK",
    "US:OR",
    "US:PA",
    "US:PR",
    "US:RI",
    "US:SC",
    "US:SD",
    "US:TN",
    "US:TX", "US:TX:FM", "US:TX:Loop", "US:TX:Spur",
    "US:UT",
    "US:VA", "US:VA:Secondary",
    "US:VT",
    "US:WA", "US:WA:Spur",
    "US:WI",
    "US:WV",
    "US:WY",
]

[crs]
osm = "EPSG:4326" # WGS-84
metric = "EPSG:8857" # WGS 84 / Equal Earth Greenwich (metre)
output = "EPSG:4326" # WGS-84

[search]
# Parameters for finding roads.
max_dist = 50 # Max meters (in metric CRS) to search for nearby road
consec_pts = 3 # Min number of consecutive points to count as road match

[output]
# Output filenames, relative to the --output directory
csv = "roads.csv"
gpkg = "20k_roads.gpkg"